SET worldPath="C:\Projects\Project\World"
SET backupPath="C:\Backup\"
SET backupPrefix="Project_"
SET checkoutPath="C:\Checkouts\"
SET remote01="\\server01\Checkouts\"
SET remote02="\\server02\Checkouts\"